sudo: required

services:
- docker

script:
# set up the base image
- sed -i "s#^FROM .*#FROM ${DOCKER_FROM}#" Dockerfile
# setup QEMU
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build
- docker build -t node_exporter:$DOCKER_TAG --build-arg ARCH=$DOCKER_ARCH --build-arg VERSION=$NODE_EXPORTER_VERSION .

after_success:
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u="rycus86" -p="$DOCKER_PASSWORD" && \
      docker tag node_exporter:$DOCKER_TAG rycus86/prometheus-node-exporter:$DOCKER_TAG && \
      docker push rycus86/prometheus-node-exporter:$DOCKER_TAG
  elif [ "$TRAVIS_BRANCH" == "$NODE_EXPORTER_VERSION" ]; then
      docker login -u="rycus86" -p="$DOCKER_PASSWORD" && \
      docker tag node_exporter:$DOCKER_TAG rycus86/prometheus-node-exporter:$NODE_EXPORTER_VERSION-$DOCKER_TAG && \
      docker push rycus86/prometheus-node-exporter:$NODE_EXPORTER_VERSION-$DOCKER_TAG
  fi

env:
  global:
  - NODE_EXPORTER_VERSION=0.14.0
  matrix:
  - DOCKER_TAG=armhf    DOCKER_ARCH=armv7  DOCKER_FROM=rycus86/armhf-alpine-qemu
  - DOCKER_TAG=aarch64  DOCKER_ARCH=arm64  DOCKER_FROM=rycus86/arm64v8-alpine-qemu
